Changed to trigger on the tag

diff --git a/.github/workflows/release_validation.yaml b/.github/workflows/release_validation.yaml
--- a/.github/workflows/release_validation.yaml
+++ b/.github/workflows/release_validation.yaml
@@ -1,8 +1,9 @@
 name: Release Validation
 
 on:
-  release:
-    types: [published]
+  push:
+    tags:
+      - v*
 
 jobs:
   release_validation:
@@ -32,10 +33,22 @@ jobs:
 
       - name: Check the pre-built GUI files are up-to-date
         run: |
+          set -e
           git status -s | grep " M "
           if [ $? -eq 0 ]; then
             echo "ERROR: The pre-built GUI files are not up-to-date"
             exit 1
           fi
 
-      ### Check the version number in the code matches the release number and tag number
+      ### Check the version number in the code matches the tag number
+      - name: Check the version number in the code matches the tag number
+        run: |
+          TAG_VERSION=$(sed "s/^v//" <<< $GITHUB_REF_NAME)
+          CODE_VERSION=$(grep BUILD_TAG platformio.ini | awk -F= '{print $NF}')
+          echo TAG_VERSION=$TAG_VERSION >> $GITHUB_ENV
+          echo CODE_VERSION=$CODE_VERSION >> $GITHUB_ENV
+          if [ "$TAG_VERSION" != "$CODE_VERSION" ]; then
+            echo "ERROR: The version number in the code ($CODE_VERSION) does not match the tag number ($TAG_VERSION)"
+            exit 1
+          fi
+
