Trigger on the `released` event and added version number checks

diff --git a/.github/workflows/release_validation.yaml b/.github/workflows/release_validation.yaml
--- a/.github/workflows/release_validation.yaml
+++ b/.github/workflows/release_validation.yaml
@@ -1,9 +1,9 @@
 name: Release Validation
 
 on:
-  push:
-    tags:
-      - v*
+  release:
+    types:
+      - released
 
 jobs:
   release_validation:
@@ -47,6 +47,17 @@ jobs:
           CODE_VERSION=$(grep BUILD_TAG platformio.ini | awk -F= '{print $NF}')
           echo TAG_VERSION=$TAG_VERSION >> $GITHUB_ENV
           echo CODE_VERSION=$CODE_VERSION >> $GITHUB_ENV
+
+      - name: Check the version numberis semver compliant
+        run: |
+          set -e
+          if ! [[ $TAG_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-z]*[0-9]+)?$ ]]; then
+            echo "ERROR: The version number is not semver compliant"
+            exit 1
+          fi
+
+      - name: Check the version number in the code matches the tag number
+        run: |
           if [ "$TAG_VERSION" != "$CODE_VERSION" ]; then
             echo "ERROR: The version number in the code ($CODE_VERSION) does not match the tag number ($TAG_VERSION)"
             exit 1
